### ISSUE TITLE
basics_01.mdについて

### ISSUE THREAD

**Issue by igaki** [oit-ipbl/robots#2]
## 全体
- READMEではROS Basicなのに，開いたらタイトルが ROS(1)になってました．どちらかに統一したほうが良いと思います

## ROS master
- `You can see the word, melodic.`のところですが，`you can see the phrase, '* /rosdistro: melodic'`.のほうが分かりやすいかもと思いました．

## Melodic morenia
- タイトルが ROS melodicのほうが良いかと思いました（moreniaの意味が分からなかったです）
- One of the LTS distribution of ROS. かなと思いました
- Ctrl+Cの↓にこれを貼り付けても親切かと思いました

```
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

## Simple publisher and subscriber(2)
- ここにvscode操作のリンクがあったほうが良いと思います．`Open ~/catkin_ws/src/oit_pbl_ros_samples/ by Visual Studio Code editor, and edit the files.`
- `Open ~/catkin_ws/src/oit_pbl_ros_samples/` 最後にscriptsが抜けてます？

## rqt_graph
- `rqt_graph`を実行するとcommand not foundになりました．もしかして何かインストール必要でしょうか？

## Advanced question
- `Check the std_msg of ROS .` ここで具体的に何をしたら良いかが分かりませんでした．何をチェックしたら良いか書いていただけませんでしょうか．

**Comment by KMiyawaki** [comment]
@igaki ありがとうございます。

## 全体、ROS master

対応しました。

## Melodic morenia

見出しに当該サイトへのリンクをつけました。

## Simple publisher and subscriber(2)

- VSCode説明リンクは準備され次第貼ります。 @jinno-oit 
- 確かにファイルはscriptsにあるのですが、パッケージ全体が入ったディレクトリを開くようにして欲しいです。プログラム以外のファイルを編集することもあるからです。今回の場合は別パッケージですが顔画像などです。

## rqt_graph

失礼しました。次の二つのファイルをインストールしていただけませんでしょうか。Dockerイメージも更新になってしまい、お手数をおかけします。

```shell
sudo apt install ros-melodic-rqt-graph
sudo apt install ros-melodic-rqt-image-view
```

## Advanced question

カットして参考資料扱い。別の場所に入れました。

**Comment by igaki** [comment]
@KMiyawaki 
rqt_graphをインストールし，コンテナを差し替えました．お手数ですが portalをDLしなおして docker-compose pullから実施ください．また，あわせてFirefoxがあまりにもイマイチだったのでブラウザをchromeに差し替えました．ちょっと特殊な設定が必要だったんですが，一応ブラウザアイコンから起動するとchromeが起動するようになっています（コピペもいけました）

**Comment by KMiyawaki** [comment]
@igaki ありがとうございます。
rqt_graph,rqt_image_viewともに起動しました。Chromeも動きました。ブックマークも再起動しても保持されてました。
